buidspecv2.5

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -13,7 +13,11 @@ phases:
     commands:
       - echo Running tests with docker-compose...
       - docker-compose build  
-      - docker-compose up test  
+      - |
+        if ! docker-compose up --abort-on-container-exit test; then
+          echo "Tests failed. Exiting with error."
+          exit 1
+        fi  
   post_build:
     commands:
       - echo Pushing Docker image to ECR...
